export const INPUT_TODO_ITEM = 'input_todo_item'
export const ADD_TODO_ITEM = 'add_todo_item'
export const DELETE_TODO_ITEM = 'delete_todo_item'
export const INIT_LIST_ITEM = 'init_list_item'
export const GET_INIT_LIST = 'get_init_list'